apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: "{{ .Values.database.image }}:{{ .Values.database.tag }}"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        {{- if .Values.database.persistent.enabled }}
        volumeMounts:
        - mountPath: /data/db
          name: storage
        {{- end }}
      {{- if .Values.database.persistent.enabled }}
      volumes:
      - name: storage
        hostPath:
          path: {{ .Values.database.persistent.hostPath }}
          type: Directory
      {{- end }} 