apiVersion: v1
kind: Secret
metadata:
  name: gh-secrets
type: Opaque
data:
  LOGIN: {{ .Values.login | b64enc }}
  PASSWORD: {{ .Values.password | b64enc }}
  DB_SERVICE: {{ .Values.dbService | b64enc }}