apiVersion: v1
kind: Service
metadata:
  name: api
  labels:
    app: api
spec:
  type: NodePort
  ports:
  - port: 5000
    nodePort: {{ .Values.api.nodePort }}
    targetPort: 5000
    protocol: TCP
    name: http
  selector:
    app: api