apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  #type: NodePort
  ports:
  - port: 27017
    #nodePort: {{ .Values.database.nodePort }}
    targetPort: 27017
    protocol: TCP
    name: http
  selector:
    app: mongodb