pullPolicy: Always
login: "greenhands.noreply@gmail.com"
password: "password"
dbService: "mongodb"

daemons:
  image: etangdesapplis/gh-daemons
  tag: "1.0.0"
  replicaCount: 1

api:
  image: etangdesapplis/gh-api
  tag: "1.0.0"
  nodePort: 32766
  replicaCount: 1

database:
  image: mongo
  tag: 4.4.1
  persistent:
    enabled: false #when activated, data is stored on host location
    hostPath: /home/ubuntu/databases/greenhands
    
